#! /bin/sh

# ] ---- AUTOSTART ---- [

sxhkd &
~/.fehbg &
setxkbmap pl &
#flameshot &
picom -f &
xset b off &
#nm-applet &
sh ~/.config/polybar/launch.sh

# ] ---- WORKSPACES ---- [ 

bspc monitor -d 一 二 三 四 五 六

# ] ---- WINDOW CONFIG ---- [

bspc config border_width         3
bspc config window_gap         	21
bspc config border_radius        10

bspc config normal_border_color "#2A2426"
bspc config focused_border_color "#62D196"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop=^2 follow=off
bspc rule -a emacs desktop=^3 follow=off
bspc rule -a Spotify desktop=^5 follow=off
bspc rule -a zoom desktop=^1 follow=off
bspc rule -a discord state=floating
bspc rule -a Brave-browser desktop=^2 follow=off
